apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base

# Set replica count to 4 (same rack)
replicas:
- name: nccl-benchmark
  count: 4

# Patch node list to include only 4 nodes from rack 4 (-nairr nodes)
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/1/values
      value:
      - moc-r4pcc04u09-nairr
      - moc-r4pcc04u11-nairr
      - moc-r4pcc04u12-nairr
      - moc-r4pcc04u16-nairr
  target:
    kind: StatefulSet
    name: nccl-benchmark
