#!/bin/bash
# Cleanup {project_name} environment
# Auto-generated by deployment wizard

PROJECT_NAME="{project_name}"
CLUSTER="{cluster_name}"
NAMESPACE="{namespace}"

echo "========================================"
echo "  Cleanup $PROJECT_NAME"
echo "========================================"
echo ""
echo "This will delete:"
echo "  - Pods/StatefulSets"
echo "  - Service accounts"
echo "  - Services and routes"
echo ""

if [ "$1" == "--all" ]; then
    echo "  - PVCs and data (--all flag specified)"
    echo ""
    echo "⚠️  WARNING: This will delete all your data!"
else
    echo "  - PVCs will be PRESERVED"
    echo ""
    echo "To delete PVCs too, use: $0 --all"
fi

echo ""
read -p "Continue? [y/N] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Cancelled"
    exit 0
fi

echo ""
echo "Cleaning up..."

# Navigate to ml-dev-env root
cd "$(dirname "$0")/../../.."

if [ "$1" == "--all" ]; then
    make clean-cluster CLUSTER="$CLUSTER" PROJECT="$PROJECT_NAME"

    # Also delete PVCs
    echo "Deleting PVCs..."
    oc delete pvc -l app={app_name} -n "$NAMESPACE" 2>/dev/null || true
else
    make clean-cluster CLUSTER="$CLUSTER" PROJECT="$PROJECT_NAME"
fi

echo ""
echo "✓ Cleanup complete!"
echo ""
echo "Your project directory is preserved: deployments/$PROJECT_NAME/"
echo "To redeploy: ./scripts/deploy.sh"
