#!/bin/bash
# Deploy {project_name} environment
# Auto-generated by deployment wizard

set -e

PROJECT_NAME="{project_name}"
CLUSTER="{cluster_name}"
MODE="{network_mode}"
NAMESPACE="{namespace}"

echo "Deploying $PROJECT_NAME..."
echo "  Cluster: $CLUSTER"
echo "  Mode: $MODE"
echo "  Namespace: $NAMESPACE"
echo ""

# Navigate to ml-dev-env root
cd "$(dirname "$0")/../../.."

# Run deployment
{deploy_command}

echo ""
echo "✓ Deployment initiated!"
echo ""
echo "Check status with: ./scripts/status.sh"
echo "Shell access with: ./scripts/shell.sh"
