#!/bin/bash
# Start Jupyter for {project_name}
# Auto-generated by deployment wizard

PROJECT_NAME="{project_name}"
NAMESPACE="{namespace}"
POD_NAME="{pod_name}"

echo "Starting Jupyter for $PROJECT_NAME..."
echo ""

# Navigate to ml-dev-env root
cd "$(dirname "$0")/../../.."

make jupyter PROJECT="$PROJECT_NAME"
