#!/bin/bash
# View logs for {project_name}
# Auto-generated by deployment wizard

PROJECT_NAME="{project_name}"
NAMESPACE="{namespace}"
POD_NAME="{pod_name}"

echo "Viewing logs for $PROJECT_NAME..."
echo "Pod: $POD_NAME"
echo ""

if [ "$1" == "-f" ] || [ "$1" == "--follow" ]; then
    echo "Following logs (Ctrl+C to stop)..."
    oc logs -f "$POD_NAME" -n "$NAMESPACE"
else
    echo "Recent logs (use -f to follow):"
    echo ""
    oc logs "$POD_NAME" -n "$NAMESPACE" --tail=50
fi
