#!/bin/bash
# Shell into {project_name} environment
# Auto-generated by deployment wizard

PROJECT_NAME="{project_name}"
NAMESPACE="{namespace}"
POD_NAME="{pod_name}"

echo "Opening shell in $PROJECT_NAME environment..."
echo "Pod: $POD_NAME"
echo "Namespace: $NAMESPACE"
echo ""

oc exec -it "$POD_NAME" -n "$NAMESPACE" -- /bin/bash
