#!/bin/bash
# Check status of {project_name}
# Auto-generated by deployment wizard

PROJECT_NAME="{project_name}"
NAMESPACE="{namespace}"
CLUSTER="{cluster_name}"

echo "========================================"
echo "  $PROJECT_NAME - Status"
echo "========================================"
echo ""

# Navigate to ml-dev-env root
cd "$(dirname "$0")/../../.."

make status-cluster CLUSTER="$CLUSTER" PROJECT="$PROJECT_NAME"
