#!/bin/bash
# Submit hyperparameter sweep jobs
# Generated by ML Dev Env deployment wizard

set -e

APP_NAME="{app_name}"
NAMESPACE="{namespace}"
CLUSTER="{cluster}"
NETWORK_MODE="{network_mode}"
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Hyperparameter Sweep Job Submission${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo

# Check if sweep is enabled in config
if ! grep -q "sweep:" "$PROJECT_DIR/config.yaml"; then
    echo -e "${RED}✗ Error: Sweep not configured in config.yaml${NC}"
    echo "  Run the deployment wizard with sweep enabled to use this script"
    exit 1
fi

# Parse sweep configuration from config.yaml
echo "📊 Reading sweep configuration..."

# Extract sweep parameters using Python
SWEEP_PARAMS=$(python3 <<'PYTHON_EOF'
import yaml
import json

with open("config.yaml") as f:
    config = yaml.safe_load(f)

sweep = config.get("application", {}).get("execution", {}).get("sweep", {})

if not sweep.get("enabled"):
    print("ERROR: Sweep not enabled")
    exit(1)

# Output as JSON for easier parsing in bash
print(json.dumps(sweep))
PYTHON_EOF
)

if [ $? -ne 0 ] || [ "$SWEEP_PARAMS" = "ERROR: Sweep not enabled" ]; then
    echo -e "${RED}✗ Error: Could not parse sweep configuration${NC}"
    exit 1
fi

# Generate all parameter combinations
echo "🔧 Generating job combinations..."

JOBS=$(python3 <<'PYTHON_EOF'
import yaml
import json
import itertools
import sys

with open("config.yaml") as f:
    config = yaml.safe_load(f)

sweep = config["application"]["execution"]["sweep"]
params = sweep["parameters"]

# Generate all combinations
param_names = [p["name"] for p in params]
param_flags = [p["flag"] for p in params]
param_values = [p["values"] for p in params]

combinations = list(itertools.product(*param_values))

# Build job specifications
jobs = []
for combo in combinations:
    # Create job ID from parameter values
    job_parts = []
    args = []
    for i, value in enumerate(combo):
        # Format for job ID (short)
        param_short = param_names[i].replace("_", "")
        if isinstance(value, float):
            value_str = f"{value:.0e}".replace("+", "").replace("0e", "e")
        else:
            value_str = str(value)
        job_parts.append(f"{param_short}{value_str}")

        # Format for CLI arguments
        args.append(f"{param_flags[i]} {value}")

    job_id = "-".join(job_parts)
    args_str = " ".join(args)

    jobs.append({
        "id": job_id,
        "args": args_str
    })

print(json.dumps(jobs))
PYTHON_EOF
)

# Parse number of jobs
TOTAL_JOBS=$(echo "$JOBS" | python3 -c "import sys, json; print(len(json.load(sys.stdin)))")

echo -e "${GREEN}✓ Generated $TOTAL_JOBS job combinations${NC}"
echo

# Read max concurrent from config
MAX_CONCURRENT=$(python3 <<'PYTHON_EOF'
import yaml
with open("config.yaml") as f:
    config = yaml.safe_load(f)
sweep = config["application"]["execution"]["sweep"]
print(sweep.get("max_concurrent", 5))
PYTHON_EOF
)

echo "📋 Sweep Summary:"
echo "  Total jobs: $TOTAL_JOBS"
echo "  Max concurrent: $MAX_CONCURRENT"
echo "  Application: $APP_NAME"
echo

# Confirm submission
read -p "Submit $TOTAL_JOBS jobs? (y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Cancelled"
    exit 0
fi

echo
echo "🚀 Submitting jobs..."
echo

# Submit jobs with concurrency control
SUBMITTED=0
RUNNING=0

for i in $(seq 0 $((TOTAL_JOBS - 1))); do
    # Extract job info
    JOB_INFO=$(echo "$JOBS" | python3 -c "import sys, json; jobs = json.load(sys.stdin); print(json.dumps(jobs[$i]))" 2>/dev/null)

    if [ -z "$JOB_INFO" ]; then
        continue
    fi

    JOB_ID=$(echo "$JOB_INFO" | python3 -c "import sys, json; print(json.load(sys.stdin)['id'])")
    JOB_ARGS=$(echo "$JOB_INFO" | python3 -c "import sys, json; print(json.load(sys.stdin)['args'])")

    # Wait if too many concurrent jobs
    while [ $RUNNING -ge $MAX_CONCURRENT ]; do
        # Count running/pending jobs
        RUNNING=$(oc get jobs -n $NAMESPACE -l app=$APP_NAME,sweep=true -o json 2>/dev/null | \
                  python3 -c "import sys, json; items = json.load(sys.stdin).get('items', []); print(len([j for j in items if j.get('status', {}).get('succeeded', 0) == 0]))" 2>/dev/null || echo "0")

        if [ $RUNNING -ge $MAX_CONCURRENT ]; then
            echo "  ⏳ Waiting for jobs to complete ($RUNNING/$MAX_CONCURRENT running)..."
            sleep 5
        fi
    done

    # Create temporary config with modified arguments
    TEMP_CONFIG=$(mktemp)
    python3 <<PYTHON_EOF
import yaml

with open("config.yaml") as f:
    config = yaml.safe_load(f)

# Update arguments with sweep parameters
base_args = config["application"]["execution"].get("arguments", "")
new_args = f"{base_args} $JOB_ARGS".strip()
config["application"]["execution"]["arguments"] = new_args

with open("$TEMP_CONFIG", "w") as f:
    yaml.dump(config, f)
PYTHON_EOF

    # Generate job manifest
    python3 ../../scripts/deploy_cluster.py \
        --cluster $CLUSTER \
        --mode $(grep "mode:" config.yaml | head -1 | awk '{print $2}') \
        --network-mode $NETWORK_MODE \
        --project $(basename "$PROJECT_DIR") \
        --job \
        --job-id "$JOB_ID" \
        --config "$TEMP_CONFIG" \
        > /dev/null 2>&1

    # Add sweep label to job manifest
    if [ -f "k8s/job-$JOB_ID.yaml" ]; then
        # Add sweep=true label
        python3 <<PYTHON_EOF
import yaml

with open("k8s/job-$JOB_ID.yaml") as f:
    job = yaml.safe_load(f)

if "labels" not in job["metadata"]:
    job["metadata"]["labels"] = {}

job["metadata"]["labels"]["sweep"] = "true"

with open("k8s/job-$JOB_ID.yaml", "w") as f:
    yaml.dump(job, f)
PYTHON_EOF

        # Apply job
        oc apply -f "k8s/job-$JOB_ID.yaml" > /dev/null 2>&1

        if [ $? -eq 0 ]; then
            echo -e "  ${GREEN}✓${NC} Job $((i + 1))/$TOTAL_JOBS: $APP_NAME-job-$JOB_ID"
            echo "     Args: $JOB_ARGS"
            SUBMITTED=$((SUBMITTED + 1))
            RUNNING=$((RUNNING + 1))
        else
            echo -e "  ${RED}✗${NC} Failed to submit job: $JOB_ID"
        fi

        # Clean up
        rm -f "k8s/job-$JOB_ID.yaml"
    fi

    rm -f "$TEMP_CONFIG"

    # Small delay between submissions
    sleep 1
done

echo
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  ✓ Submitted $SUBMITTED/$TOTAL_JOBS jobs${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo
echo "📊 Monitor sweep progress:"
echo "  ./scripts/watch-sweep.sh"
echo
echo "📋 List all sweep jobs:"
echo "  oc get jobs -n $NAMESPACE -l app=$APP_NAME,sweep=true"
echo
