#!/bin/bash
# Sync code to {project_name} environment
# Auto-generated by deployment wizard

PROJECT_NAME="{project_name}"
NAMESPACE="{namespace}"
POD_NAME="{pod_name}"

# Navigate to ml-dev-env root
cd "$(dirname "$0")/../../.."

if [ "$1" == "--watch" ]; then
    echo "Starting auto-sync mode for $PROJECT_NAME..."
    echo "Watching: deployments/$PROJECT_NAME/workspace/"
    echo "Target: $POD_NAME:/workspace"
    echo ""
    echo "Press Ctrl+C to stop"
    echo ""

    make dev-session PROJECT="$PROJECT_NAME"
else
    echo "Syncing code to $PROJECT_NAME..."
    make sync-{sync_target} PROJECT="$PROJECT_NAME"
    echo "✓ Sync complete"
fi
