#!/bin/bash
# Open VSCode for {project_name}
# Auto-generated by deployment wizard

PROJECT_NAME="{project_name}"
NAMESPACE="{namespace}"

echo "Getting VSCode URL for $PROJECT_NAME..."

VSCODE_URL=$(oc get route {app_name}-vscode -n "$NAMESPACE" -o jsonpath='https://{{.spec.host}}' 2>/dev/null)

if [ -z "$VSCODE_URL" ]; then
    echo "✗ VSCode route not found"
    echo ""
    echo "Make sure VSCode is enabled and deployed"
    echo "Check status with: ./scripts/status.sh"
    exit 1
fi

echo ""
echo "VSCode URL: $VSCODE_URL"
echo ""

# Try to open in browser (macOS/Linux)
if command -v open &> /dev/null; then
    echo "Opening in browser..."
    open "$VSCODE_URL"
elif command -v xdg-open &> /dev/null; then
    echo "Opening in browser..."
    xdg-open "$VSCODE_URL"
else
    echo "Copy and paste the URL above into your browser"
fi
