apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: h100
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - worker
      - h100
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/h100: ""
  maxUnavailable: 0
