#!/usr/bin/env bash
#
# Launch wrapper for auto-detected GPU-to-NIC affinity
#
# This wrapper sets NCCL_IB_HCA to all available HCAs and lets
# NCCL automatically detect topology and choose local HCAs.
#
# Usage:
#   torchrun --nproc_per_node=4 launch-with-auto-affinity.sh train.py [args]
#
# This is simpler than explicit affinity and works well in most cases.

set -euo pipefail

LOCAL_RANK="${LOCAL_RANK:-0}"

log() {
    echo "[AUTO-AFFINITY-LAUNCHER] [Rank $LOCAL_RANK] $*" >&2
}

log "Starting with auto-detected GPU-to-NIC affinity..."

# Source the NCCL configuration generated by detect-gpu-nic-affinity.sh
if [[ -f /shared/nccl-env.sh ]]; then
    log "Loading NCCL configuration from /shared/nccl-env.sh"
    source /shared/nccl-env.sh

    log "NCCL Configuration:"
    log "  NCCL_IB_HCA=$NCCL_IB_HCA"
    log "  NCCL_SOCKET_IFNAME=$NCCL_SOCKET_IFNAME"
    log "  NCCL_NET_GDR_LEVEL=$NCCL_NET_GDR_LEVEL"
else
    log "WARNING: /shared/nccl-env.sh not found"
    log "Falling back to manual configuration..."

    # Fallback: detect available HCAs
    if command -v ibv_devinfo &>/dev/null; then
        IB_DEVICES=$(ibv_devinfo -l 2>/dev/null | grep -v "^$" | tr '\n' ',' | sed 's/,$//' || echo "")
        export NCCL_IB_HCA="$IB_DEVICES"
        log "Detected IB HCAs: $NCCL_IB_HCA"
    else
        log "ERROR: ibv_devinfo not found, RDMA may not work"
    fi

    # Detect RDMA interfaces
    RDMA_IFACES=$(ip -o link show | awk -F': ' '{print $2}' | grep -E '^net[0-9]+$' | tr '\n' ',' | sed 's/,$//' || echo "eth0")
    export NCCL_SOCKET_IFNAME="$RDMA_IFACES"
    log "Detected RDMA interfaces: $NCCL_SOCKET_IFNAME"

    # Set other NCCL parameters
    export NCCL_NET_GDR_LEVEL=5
    export NCCL_IB_DISABLE=0
    export NCCL_IB_GID_INDEX=3
    export NCCL_P2P_LEVEL=NVL
fi

log "NCCL will auto-detect topology and prefer local HCAs"
log "Starting training..."

# Run training
exec python "$@"
